mutag:
  learning_rate: 0.01
  initial_temp: 5.0
  final_temp: 1.0
  num_epochs: 20
bgs:
  learning_rate: 0.01
  initial_temp: 5.0
  final_temp: 1.0
  num_epochs: 40
aifb:
  learning_rate: 0.01
  initial_temp: 5.0
  final_temp: 1.0
  num_epochs: 20
